
import { createClient } from '@supabase/supabase-js';

// Use environment variables if available, otherwise use placeholder values
// WARNING: In a production environment, these should be set as environment variables
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || 'https://your-supabase-url.supabase.co';
const supabaseKey = import.meta.env.VITE_SUPABASE_ANON_KEY || 'your-supabase-anon-key';

// Verificar se as credenciais são válidas
const isValidSupabaseConfig = 
  supabaseUrl !== 'https://your-supabase-url.supabase.co' &&
  supabaseKey !== 'your-supabase-anon-key';

export const supabaseConfigured = isValidSupabaseConfig;

export const supabase = createClient(supabaseUrl, supabaseKey);

// Tipagem para produtos
export interface Product {
  id: number;
  name: string;
  price: number;
  image: string;
  category: string;
}

/*
Para configurar o banco de dados no Supabase, crie uma tabela 'products' com a seguinte estrutura SQL:

create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric not null,
  image text not null,
  category text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

// Adicione permissão para acesso anônimo (somente para desenvolvimento)
alter table public.products enable row level security;
create policy "Allow anonymous access to products" on products for all using (true);
*/
