
import { createClient } from '@supabase/supabase-js';

const supabaseUrl = 'YOUR_SUPABASE_URL';
const supabaseKey = 'YOUR_SUPABASE_ANON_KEY';

export const supabase = createClient(supabaseUrl, supabaseKey);

// Tipagem para produtos
export interface Product {
  id: number;
  name: string;
  price: number;
  image: string;
  category: string;
}

/*
Para configurar o banco de dados no Supabase, crie uma tabela 'products' com a seguinte estrutura SQL:

create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric not null,
  image text not null,
  category text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

// Adicione permissão para acesso anônimo (somente para desenvolvimento)
alter table public.products enable row level security;
create policy "Allow anonymous access to products" on products for all using (true);
*/
