
version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: lia_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lia_password
    ports:
      - "5432:5432"
    networks:
      - lia-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - lia-network

  backend:
    build: 
      context: ./django_backend
      dockerfile: Dockerfile.django
    ports:
      - "8000:8000"
    volumes:
      - ./django_backend:/app
    environment:
      - DEBUG=True
      - DB_NAME=lia_db
      - DB_USER=postgres
      - DB_PASSWORD=lia_password
      - DB_HOST=db
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CORS_ALLOWED_ORIGINS=http://localhost:8080,http://127.0.0.1:8080
    depends_on:
      - db
      - redis
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    networks:
      - lia-network

  celery:
    build: 
      context: ./django_backend
      dockerfile: Dockerfile.django
    volumes:
      - ./django_backend:/app
    environment:
      - DEBUG=True
      - DB_NAME=lia_db
      - DB_USER=postgres
      - DB_PASSWORD=lia_password
      - DB_HOST=db
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
      - backend
    command: celery -A lia_project worker -l info
    networks:
      - lia-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - VITE_DJANGO_API_URL=http://backend:8000/api
    depends_on:
      - backend
    networks:
      - lia-network

volumes:
  postgres_data:

networks:
  lia-network:
    driver: bridge
