// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xegkqqtphhhhhelhxbgl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhlZ2txcXRwaGhoaGhlbGh4YmdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxNDg4MTIsImV4cCI6MjA1NzcyNDgxMn0.nZuijowIj85GLYmQIWMc-hjJbfd-q-bxeXzkkzk5hH0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);